Add a comment advising blurb-it if a news entry is missing
python/bedevere pull request #379
Opened 2021-12-07 12:48 UTC by arhadthedev

~*Since I have no possibility to test the addition, I make this PR draft until maintainers check it.*~

This PR complements `No news entry` status with a comment recommending https://blurb-it.herokuapp.com so a new contributor will know how to generate a NEWS entry. The comment is a verbatim copy of [the one by Serhiy Storchaka](https://github.com/python/cpython/pull/29947#issuecomment-987846284).

2021-12-07 19:08 UTC, brettcannon commented
Without commenting on whether we would take this, the test suite allows you to test whether this would work (and we require 100% test coverage and so a test would be necessary).

2022-04-12 07:57 UTC, arhadthedev commented
I added the test, could you approve the run please?

In addition I rephrased the message to mention the offline tool:

> To inform end users, a NEWS entry is necessary. See [Updating NEWS and What’s New in Python](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python) for more details.
>
> Please, add it using https://blurb-it.herokuapp.com site or [blurb PyPI package](https://pypi.org/project/blurb/); they both take care on names and placement.

If it can be further improved, I'll happily make edits.

2022-04-12 18:00 UTC, Mariatta commented
Somehow the coverage bot is not triggered here. Not sure what's going on, but perhaps you need to rebase with the latest change.

I think we were trying to avoid posting too many bot messages :) If people find this message useful instead of too noisy, then perhaps it's ok.

2022-04-12 18:07 UTC, AlexWaygood commented
>  If people find this message useful instead of too noisy, then perhaps it's ok.

I would have found this useful when I was new to contributing to CPython. I didn't learn about the blurb_it website until a few months after I'd started contributing. I actually didn't realise that the "Details" button in the CI check linked straight to blurb_it until a few weeks ago.

I also understand the concern about too many comments by bots, though. Ideally I guess I'd like to see the comment only triggered if it's a PR by a first-time contributor, but I guess that would add some complexity.

2022-04-12 22:55 UTC, Mariatta commented
> I guess I'd like to see the comment only triggered if it's a PR by a first-time contributor, but I guess that would add some complexity.

The `pull_request` webhook payload includes the `"author_association"` info. The values could be: `"OWNER"`, `"MEMBER"`, `"CONTRIBUTOR"`, or `"NONE"`.
In this case, we can issue the bot comment if the `"author_association"` field is `"NONE"`.


Example real webhook payload data:

<details>

```

{
  "action": "opened",
  "number": 91478,
  "pull_request": {
    "url": "https://api.github.com/repos/python/cpython/pulls/91478",
    "id": 907417240,
    "node_id": "PR_kwDOBN0Z8c42FhaY",
    "html_url": "https://github.com/python/cpython/pull/91478",
    "diff_url": "https://github.com/python/cpython/pull/91478.diff",
    "patch_url": "https://github.com/python/cpython/pull/91478.patch",
    "issue_url": "https://api.github.com/repos/python/cpython/issues/91478",
    "number": 91478,
    "state": "open",
    "locked": false,
    "title": "updated tutorial example code output",
    "user": {
      "login": "alex-krav",
      "id": 7326297,
      "node_id": "MDQ6VXNlcjczMjYyOTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7326297?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/alex-krav",
      "html_url": "https://github.com/alex-krav",
      "followers_url": "https://api.github.com/users/alex-krav/followers",
      "following_url": "https://api.github.com/users/alex-krav/following{/other_user}",
      "gists_url": "https://api.github.com/users/alex-krav/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/alex-krav/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/alex-krav/subscriptions",
      "organizations_url": "https://api.github.com/users/alex-krav/orgs",
      "repos_url": "https://api.github.com/users/alex-krav/repos",
      "events_url": "https://api.github.com/users/alex-krav/events{/privacy}",
      "received_events_url": "https://api.github.com/users/alex-krav/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "<!--\r\nThanks for your contribution!\r\nPlease read this comment in its entirety. It's quite important.\r\n\r\n# Pull Request title\r\n\r\nIt should be in the following format:\r\n\r\n```\r\ngh-NNNNN: Summary of the changes made\r\n```\r\n\r\nWhere: gh-NNNNN refers to the GitHub issue number.\r\n\r\nMost PRs will require an issue number. Trivial changes, like fixing a typo, do not need an issue.\r\n\r\n# Backport Pull Request title\r\n\r\nIf this is a backport PR (PR made against branches other than `main`),\r\nplease ensure that the PR title is in the following format:\r\n\r\n```\r\n[X.Y] <title from the original PR> (GH-NNNN)\r\n```\r\n\r\nWhere: [X.Y] is the branch name, e.g. [3.6].\r\n\r\nGH-NNNN refers to the PR number from `main`.\r\n\r\n-->\r\n",
    "created_at": "2022-04-12T09:45:57Z",
    "updated_at": "2022-04-12T09:45:57Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/python/cpython/pulls/91478/commits",
    "review_comments_url": "https://api.github.com/repos/python/cpython/pulls/91478/comments",
    "review_comment_url": "https://api.github.com/repos/python/cpython/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/python/cpython/issues/91478/comments",
    "statuses_url": "https://api.github.com/repos/python/cpython/statuses/4b214f4208c69680a0381c2ca55fd21aab1b7cc7",
    "head": {
      "label": "alex-krav:docs-update",
      "ref": "docs-update",
      "sha": "4b214f4208c69680a0381c2ca55fd21aab1b7cc7",
      "user": {
        "login": "alex-krav",
        "id": 7326297,
        "node_id": "MDQ6VXNlcjczMjYyOTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7326297?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alex-krav",
        "html_url": "https://github.com/alex-krav",
        "followers_url": "https://api.github.com/users/alex-krav/followers",
        "following_url": "https://api.github.com/users/alex-krav/following{/other_user}",
        "gists_url": "https://api.github.com/users/alex-krav/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alex-krav/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alex-krav/subscriptions",
        "organizations_url": "https://api.github.com/users/alex-krav/orgs",
        "repos_url": "https://api.github.com/users/alex-krav/repos",
        "events_url": "https://api.github.com/users/alex-krav/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alex-krav/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 479493720,
        "node_id": "R_kgDOHJR-WA",
        "name": "cpython",
        "full_name": "alex-krav/cpython",
        "private": false,
        "owner": {
          "login": "alex-krav",
          "id": 7326297,
          "node_id": "MDQ6VXNlcjczMjYyOTc=",
          "avatar_url": "https://avatars.githubusercontent.com/u/7326297?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/alex-krav",
          "html_url": "https://github.com/alex-krav",
          "followers_url": "https://api.github.com/users/alex-krav/followers",
          "following_url": "https://api.github.com/users/alex-krav/following{/other_user}",
          "gists_url": "https://api.github.com/users/alex-krav/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/alex-krav/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/alex-krav/subscriptions",
          "organizations_url": "https://api.github.com/users/alex-krav/orgs",
          "repos_url": "https://api.github.com/users/alex-krav/repos",
          "events_url": "https://api.github.com/users/alex-krav/events{/privacy}",
          "received_events_url": "https://api.github.com/users/alex-krav/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/alex-krav/cpython",
        "description": "The Python programming language",
        "fork": true,
        "url": "https://api.github.com/repos/alex-krav/cpython",
        "forks_url": "https://api.github.com/repos/alex-krav/cpython/forks",
        "keys_url": "https://api.github.com/repos/alex-krav/cpython/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/alex-krav/cpython/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/alex-krav/cpython/teams",
        "hooks_url": "https://api.github.com/repos/alex-krav/cpython/hooks",
        "issue_events_url": "https://api.github.com/repos/alex-krav/cpython/issues/events{/number}",
        "events_url": "https://api.github.com/repos/alex-krav/cpython/events",
        "assignees_url": "https://api.github.com/repos/alex-krav/cpython/assignees{/user}",
        "branches_url": "https://api.github.com/repos/alex-krav/cpython/branches{/branch}",
        "tags_url": "https://api.github.com/repos/alex-krav/cpython/tags",
        "blobs_url": "https://api.github.com/repos/alex-krav/cpython/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/alex-krav/cpython/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/alex-krav/cpython/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/alex-krav/cpython/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/alex-krav/cpython/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/alex-krav/cpython/languages",
        "stargazers_url": "https://api.github.com/repos/alex-krav/cpython/stargazers",
        "contri [...]

2022-04-12 23:26 UTC, Mariatta requested changes
The `issue_comment_url` you're using is not correct.
Also, let's check if the user is a first-time contributor by checking the `"author_association"` field.

2022-04-12 23:26 UTC, Mariatta commented on bedevere/news.py
> +            await gh.post(pull_request['issue_comment_url'],
Add before this:

```
if pull_request['author_association'] == 'NONE':
```

2022-04-12 23:26 UTC, Mariatta commented on bedevere/news.py
> +            await gh.post(pull_request['issue_comment_url'],
`pull_request['issue_comment_url']` is not the right POST url.

API doc: https://docs.github.com/en/rest/reference/issues#create-an-issue-comment

The path is `/repos/{owner}/{repo}/issues/{issue_number}/comments`, so this should look like:
```suggestion
            await gh.post(f"{pull_request['issue_url']}/comments",
```

2022-04-13 18:46 UTC, arhadthedev commented
@ambv The status went green because I've resigned the CLA.

2022-04-15 11:22 UTC, ambv commented on bedevere/news.py
> +package]({BLURB_PYPI_URL}); they both take care on names and placement."""
```suggestion
Every change to Python [requires a NEWS entry]\
(https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).

Please, add it using the [blurb_it]({BLURB_IT_URL}) Web app or the [blurb]\
({BLURB_PYPI_URL}) command-line tool."""
```

2022-04-15 11:43 UTC, merged

2022-04-15 13:28 UTC, AlexWaygood commented
Thanks @arhadthedev, this is great! 😀 https://github.com/python/cpython/pull/47246#issuecomment-1100101716