Move to GH Actions
python/bedevere pull request #459
Opened 2022-05-21 02:29 UTC by sabderemane

Related to #344

2022-05-22 00:02 UTC, ezio-melotti reviewed
An early review with a few comments.

2022-06-24 11:13 UTC, arhadthedev commented
@sabderemane Would you mind to address the reviews, please? It would be great to retire a third party Heroku service of extra maintainance, not-so-transparent deployment, non-public error logs, and a dedicated, actively waiting server loop.

2022-06-24 11:41 UTC, sabderemane commented
I will, for sure, I just didn't have time to do so yet :)

2022-07-14 13:21 UTC, sabderemane reviewed
Thank you @ezio-melotti for the review 👍🏽

2022-07-14 13:21 UTC, sabderemane commented on .github/workflows/review_pr.yml
> +            ${{ runner.os }}-pip-
I update the `key` but for the rest it should be ok, I use [this example](https://github.com/actions/cache/blob/main/examples.md#simple-example)

2022-07-14 13:21 UTC, sabderemane commented on .github/workflows/review_pr.yml
> +          python-version: '3.9'
No, I changed

2022-07-14 13:21 UTC, sabderemane commented on bedevere/backport.py
> +        if event.get("action") == "edited" and "title" not in event.get("changes"):
No, I only keep `event` only, changed

2022-07-14 13:21 UTC, sabderemane commented on bedevere/review_pr.py
> +loop.run_until_complete(main())
updated

2022-07-14 13:21 UTC, sabderemane commented on .github/workflows/review_pr.yml
> +    name: Check and update backport label of PR
Updated

2022-07-14 13:33 UTC, hugovk reviewed
A few workflow suggestions :)

2022-07-14 13:33 UTC, hugovk commented on CONTRIBUTING.rst
> +Bedevere web service is currently launched with GitHub Actions, which is managed by The PSF.
"currently" is redundant
```suggestion
Bedevere web service is launched with GitHub Actions, which is managed by The PSF.
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/review_pr.yml
> +            ${{ runner.os }}-pip-
`actions/setup-python` now natively includes pip caching.

Docs: https://github.com/actions/setup-python#caching-packages-dependencies

So we can remove the `uses: actions/cache@v1` step, and update:


```diff
-      - uses: actions/setup-python@v3
+      - uses: actions/setup-python@v4
         with:
           python-version: '3.x'
+          cache: pip
+          cache-dependency-path: '*requirements.txt'
```

And the same in the other workflows.

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/review_pr.yml
> +      - uses: actions/checkout@v2
Bump:
```suggestion
      - uses: actions/checkout@v3
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/close_pr.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/close_pr.yml
> +      - uses: actions/setup-python@v3
```suggestion
      - uses: actions/setup-python@v4
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/backport.yml
> +      - uses: actions/checkout@v2
Bump version:
```suggestion
      - uses: actions/checkout@v3
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/backport.yml
> +      - uses: actions/setup-python@v3
```suggestion
      - uses: actions/setup-python@v4
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/filepaths.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2022-07-14 13:33 UTC, hugovk commented on .github/workflows/filepaths.yml
> +      - uses: actions/setup-python@v3
```suggestion
      - uses: actions/setup-python@v4
```

2022-07-14 13:43 UTC, hugovk commented on .github/workflows/close_pr.yml
> +          python-version: '3.9'
Dependency path: we install `dev-requirements.txt`, which includes installing `-r requirements.txt`

below I suggest using `cache-dependency-path: '*requirements.txt'`, so if either of those files change, it invalidates the cache and downloads the new things.

2022-07-14 19:18 UTC, ezio-melotti requested changes
I left some more review comments.
* It seems that some of the changes applied lately got lost during a merge -- those should be double checked and fixed;
* there were some formatting problems likely caused by a misconfigured editor (trailing spaces, tabs, changed indentation)

P.S.: you can probably batch merge most of these directly from GitHub.

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/backport.py
> +    return "no labels"
Why were the return values added?  ISTM that they are not used.

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/backport.py
> -    return bool(re.fullmatch(maintenance_branch_pattern, ref))
I think this got accidentally deleted during the merge (like the `re.IGNORECASE` above).

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/backport.py
> +    if base_branch == "main":
This should also use `not is_maintanance_branch`.
You should double check that there aren't other updates that got revert during the merge (or possibly re-do the merge).

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/close_pr.py
> +        base_label = event["pull_request"]["base"]["label"]
```suggestion
    head_label = event["pull_request"]["head"]["label"]
    base_label = event["pull_request"]["base"]["label"]
```

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/filepaths.py
> +        pull_request = event['pull_request']
```suggestion
    pull_request = event['pull_request']
```

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/review_pr.py
> +        base_label = event["pull_request"]["base"]["label"]
```suggestion
    head_label = event["pull_request"]["head"]["label"]
    base_label = event["pull_request"]["base"]["label"]
```

2022-07-14 19:18 UTC, ezio-melotti commented on bedevere/review_pr.py
> +                        data=data)
```suggestion
    if (PYTHON_MAINT_BRANCH_RE.match(head_label) and
        base_label == "python:main"):
        pr = event["pull_request"]
        reviewers = [reviewer["login"] for reviewer in pr["requested_reviewers"]
        team_reviewers = [team["name"] for team in pr["requested_teams"]
        await gh.delete(f'{event["pull_request"]["url"]}/requested_reviewers',
                        data=dict(reviewers=reviewers, team_reviewers=team_reviewers))
```

2022-10-03 21:50 UTC, sabderemane commented
Sorry for the late update, I address all the issues hopefully, thank you for the review @hugovk, @ezio-melotti and @DanielNoord.  I change my configuration to avoid editor issue 🙏🏽  I will see to continue and update tests.

2023-06-15 03:51 UTC, arhadthedev commented
From https://github.com/python/bedevere/issues/344#issuecomment-1591861785:

> One issue with using Actions is that it require maintainers to "approve" the workflow for contributors before it can be run.
The workflows done by bedevere, like checking for skip issue, skip news, applying "type" labels, should just run by itself without needing maintainer approval.
>
> So I think it would be better to convert bedevere into GitHub App instead of Actions. By converting this to GitHub App, we can resolve the issue where 2FA is needed for the bedevere-bot account.

From the following https://github.com/python/bedevere/issues/344#issuecomment-1591889387:

> To solve the issue where core devs want to be able to re-run workflows/retrigger webhook in case the web app is down, we can grant the "[GitHub App manager](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/adding-and-removing-github-app-managers-in-your-organization#about-github-app-managers)" access to core devs.

The problem surfaced while working on gh-568 so gh-569 was created instead.

@sabderemane Probably, your PR is a dead-end then. We need to either close it in favor of gh-569 or think on some alterations.

2023-06-15 06:31 UTC, closed without merging

2023-06-15 06:33 UTC, sabderemane commented
Closing in favor of gh-569, happy to help on other things instead :)